# Generated by Django 5.2.7 on 2025-12-24 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('email', 'shop', 'role')},
        ),
    ]
