# Generated by Django 5.2.7 on 2026-01-22 11:24

import django.core.validators
import django.db.models.deletion
import shops.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.CharField(default=shops.models.default_category_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.CharField(default=shops.models.default_property_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=shops.models.default_product_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_end_at', models.DateTimeField(blank=True, null=True)),
                ('currency_unit', models.CharField(default='EUR', max_length=5)),
                ('condition', models.CharField(blank=True, max_length=20, null=True)),
                ('warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_term', models.TextField(blank=True, null=True)),
                ('refund', models.BooleanField(default=False)),
                ('refund_policy', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='products', to='shops.productcategory')),
                ('properties', models.ManyToManyField(related_name='products', to='shops.productproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.CharField(default=shops.models.default_product_image_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('media', models.FileField(upload_to='product_media/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.product')),
            ],
            options={
                'ordering': ['order', '-is_primary', 'updated_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.CharField(default=shops.models.default_rating_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='customers.guestuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='shops.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(default=shops.models.default_shop_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=255)),
                ('country', models.CharField(default='Finland', max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('media', models.FileField(blank=True, null=True, upload_to='shop_media/')),
                ('template', models.CharField(default='Template-1', max_length=100)),
                ('policy', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='shops', to='shops.productcategory')),
                ('shop_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.CharField(default=shops.models.default_order_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_number', models.CharField(max_length=255)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Pending', max_length=11)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.guestuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='GuestUserRating',
            fields=[
                ('id', models.CharField(default=shops.models.default_rating_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='customers.guestuser')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopRating',
            fields=[
                ('id', models.CharField(default=shops.models.default_rating_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_ratings', to='customers.guestuser')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_ratings', to='shops.shop')),
            ],
        ),
    ]
