# Generated by Django 5.2.7 on 2026-01-14 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_guestuser_last_login_and_more'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.guestuser'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order_items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
