# Generated by Django 5.2.7 on 2025-12-20 10:26

import shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='template',
            field=models.CharField(default='template-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=shops.models.default_shop_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.CharField(default=shops.models.default_shop_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.CharField(default=shops.models.default_shop_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
