# Generated by Django 5.2.7 on 2026-01-22 22:13

import django.db.models.deletion
import shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_product_options_productproperty_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertyValue',
            fields=[
                ('id', models.CharField(default=shops.models.default_property_value_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='shops.product')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='shops.productproperty')),
            ],
            options={
                'ordering': ['property__name'],
                'unique_together': {('product', 'property')},
            },
        ),
    ]
