# Generated by Django 5.2.7 on 2026-01-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_productpropertyvalue'),
    ]

    operations = [
        # Step 1: Remove the old many-to-many field
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        # Step 2: Add it back with the through model
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(
                related_name='products',
                through='shops.ProductPropertyValue',
                to='shops.productproperty'
            ),
        ),
    ]
